services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.0
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      cockroach start-single-node --insecure &
      sleep 8 &&
      cockroach sql --insecure --host=localhost:26257 -e 'CREATE DATABASE IF NOT EXISTS nakama;' &&
      wait
      "
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data

  nakama:
    build:
      context: ../nakama
    depends_on:
      - cockroachdb
    ports:
      - "7350:7350"
      - "7349:7349"
    command:
      - "/nakama/nakama"
      - "--config"
      - "/nakama/data/local.yml"
    # environment:
    #   - DATABASE_ADDRESS=root@cockroachdb:26257
    restart: unless-stopped

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: sh -c "corepack enable && pnpm install && pnpm dev --host"
    ports:
      - "5173:5173"
    depends_on:
      - nakama


volumes:
  cockroach_data: