events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:4173;
    }

    location /ws {
      proxy_pass http://nakama:7350;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /rpc {
      proxy_pass http://nakama:7350;
    }
  }
}